rendering
iconSVG
	^ '<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <line fill="none" stroke="#999999" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="2.55034" y1="4.07194" x2="22.47507" y2="4.07194" id="svg_1"/>
  <line stroke="#999999" fill="none" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="2.55034" y1="8.57702" x2="12.20724" y2="8.57702" id="svg_4"/>
  <path fill="#999999" stroke="#999999" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" d="m23.07321,24.48483l-7.35073,-7.3583l4.84105,0l7.35061,7.3583l-7.35061,7.3583l-4.84105,0l7.35073,-7.3583z" id="svg_8" transform="rotate(90.3493 21.8183 24.4848)"/>
  <line id="svg_3" stroke="#999999" fill="none" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="2.55034" y1="22.09226" x2="12.20724" y2="22.09226"/>
  <path fill="#999999" stroke="#999999" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" d="m22.84293,14.02426l-7.35073,-7.3583l4.84105,0l7.35061,7.3583l-7.35061,7.3583l-4.84105,0l7.35073,-7.3583z" transform="rotate(90.3493 21.588 14.0243)" id="svg_9"/>
  <line stroke="#999999" fill="none" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="18.19298" y1="8.57702" x2="22.46256" y2="8.57702" id="svg_10"/>
  <line fill="none" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="2.55034" y1="26.59734" x2="14.09062" y2="26.59734" id="svg_12" stroke="#999999"/>
  <line id="svg_2" stroke="#999999" fill="none" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="2.55034" y1="17.58718" x2="12.20724" y2="17.58718"/>
  <line id="svg_5" stroke="#999999" fill="none" stroke-width="2" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="2.61917" y1="13.0821" x2="12.27607" y2="13.0821"/>
 </g>
</svg>'