*Kobold-RefactoringsServer
additionalAttributes
	^ {{('id' -> 1).
	('label' -> 'xpath').
	('description' -> 'Element''s XPath').
	('type' -> 'X')} asDictionary.
	{{('id' -> 2).
	('label' -> 'frequentValue').
	('description' -> 'A frequent value for this input').
	('type' -> 'T')} asDictionary.
	{('id' -> 2).
	('label' -> 'frequentValue').
	('description' -> 'A frequent value for this input').
	('type' -> 'T')} asDictionary}}