*Kobold-RefactoringsServer
additionalAttributes
	^ {{('id' -> 1).
	('label' -> 'home').
	('description' -> 'URL of the page with the long contents.').
	('type' -> 'S')} asDictionary.
	{{('id' -> 2).
	('label' -> 'section').
	('description' -> 'XPath to the section').
	('type' -> 'X')} asDictionary.
	{('id' -> 3).
	('label' -> 'sectionName').
	('description' -> 'Section''s name').
	('type' -> 'T')} asDictionary}}