rendering
iconSVG
	^ '<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <ellipse stroke="#999999" ry="11.079164" rx="11.079164" id="svg_23" cy="15.520265" cx="16.133485" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="5,5" stroke-width="6" fill="none"/>
 </g>
</svg>'