printing
iconSVG

	^'<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <ellipse stroke="#999999" ry="4.73868" rx="4.73868" id="svg_4" cy="7.97842" cx="7.12332" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" fill="none"/>
  <line id="svg_7" y2="7.64471" x2="40.76927" y1="7.64471" x1="15.46606" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="5" stroke="#999999" fill="none"/>
  <ellipse id="svg_11" stroke="#999999" ry="4.73868" rx="4.73868" cy="21.26007" cx="7.39127" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" fill="none"/>
  <line id="svg_12" y2="20.92636" x2="41.03722" y1="20.92636" x1="15.73402" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="5" stroke="#999999" fill="none"/>
 </g>
</svg>'