printing
iconSVG

	^'<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <circle fill-opacity="0.01" stroke="#000000" id="svg_1" r="7.27052" cy="12.009014" cx="19.491435" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="3" fill="#ffffff"/>
  <rect stroke="#000000" transform="rotate(45 10.517384529113773,21.264625549316403) " id="svg_2" height="12.968936" width="3.068258" y="14.780157" x="8.983256" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" fill="#000000"/>
 </g>
</svg>'