uploaded
mainCssContent

	^'
	
	.reporterAction{padding-right:20px}
	.ignore{color:rgb(240,100,100); font-size:.9em}
.register{margin:30px 0}
.jumbotron{background:none; min-height:450px}
.tracking{margin:30px;padding:30px;}

      /* Set the fixed height of the footer here */
      #push,
      #footer {
		margin:20px 0;
      }
      #footer {
        background-color: #eee;
      }
      /* Lastly, apply responsive CSS fixes as necessary */
      @media (max-width: 767px) {
        #footer {
          margin-left: -20px;
          margin-right: -20px;
          margin-top: 20px;
          padding: 20px;
        }
      }

	.credit {
        margin: 20px 0;
      }
	.muted{color:#999}
	.us-group h5 a{color: black}
	.us-group h5 a:hover{color: #337ab7}
	.media {margin:40px 0}
	.us-group a{cursor:pointer}
	.svg-bg{width:64px;height:64px; padding:16px; background-color:#eee}
	.us-modal{width:700px}
'