printing
iconSVG

	^'<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <line stroke-width="4" id="svg_1" y2="3.90717" x2="29.61536" y1="27.53381" x1="1.85071" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke="#999999" fill="none"/>
  <line stroke-width="4" id="svg_2" y2="28.73517" x2="27.88007" y1="2.43884" x1="2.65161" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke="#999999" fill="none"/>
 </g>
</svg>'