printing
iconSVG

	^'
<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <line id="svg_2" y2="15.60369" x2="11.09861" y1="15.60369" x1="3.59014" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="8" stroke="#999999" fill="none"/>
  <line stroke="#999999" id="svg_4" y2="15.7038" x2="30.82085" y1="15.7038" x1="20.50922" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="8" fill="none"/>
  <line id="svg_5" y2="1.63794" x2="20.20474" y1="28.96877" x1="10.49379" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" stroke="#999999" fill="none"/>
 </g>
</svg>
'