printing
iconSVG

	^'<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <rect stroke="#999999" fill="none" stroke-width="2" x="2.19231" y="7.71051" width="20.11528" height="13.75626" id="svg_1"/>
  <line transform="rotate(-1.17137 17.9397 14.2772)" stroke="#999999" fill="none" stroke-width="8" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="4.89906" y1="14.03987" x2="30.98033" y2="14.51448" id="svg_2"/>
  <line fill="none" stroke="#000000" stroke-width="5" stroke-dasharray="null" stroke-linejoin="null" stroke-linecap="null" x1="-19.49512" y1="-6.09765" x2="-19.73242" y2="-6.09765" id="svg_3"/>
 </g>
</svg>'