printing
iconSVG

	^'<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <rect stroke="#999999" id="svg_9" height="11.15933" width="10.96006" y="3.50579" x="2.37018" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" fill="none"/>
  <path id="svg_12" d="m3.99035,9.15345l0.73983,-0.74011l2.02673,2.02649l3.37853,-3.37747l0.74007,0.73956l-4.1186,4.11808" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" stroke="#999999" fill="none"/>
  <rect id="svg_14" stroke="#999999" height="11.15933" width="10.96006" y="18.83653" x="2.56634" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" fill="none"/>
  <rect id="svg_20" height="6.57154" width="25.25347" y="5.55163" x="18.81637" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" stroke="#999999" fill="#999999"/>
  <rect id="svg_22" height="6.57154" width="25.25347" y="20.90086" x="18.64777" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" stroke="#999999" fill="#999999"/>
 </g>
</svg>'