printing
iconSVG

	^'<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->

 <g>
  <title>Layer 1</title>
  <rect stroke="#999999" id="svg_7" height="5.00565" width="21.12383" y="6.64358" x="5.34212" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" fill="none"/>
  <rect id="svg_8" stroke="#999999" height="5.00565" width="21.12383" y="14.70267" x="5.69251" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" fill="none"/>
  <rect stroke="#999999" id="svg_6" height="28.73241" width="28.03162" y="1.63794" x="1.98419" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" fill="none"/>
  <rect id="svg_9" stroke="#999999" height="5.00565" width="21.12383" y="22.31126" x="5.79262" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" fill="none"/>
  <text stroke="#999999" font-weight="bold" xml:space="preserve" text-anchor="middle" font-family="Sans-serif" font-size="24" id="svg_10" y="23.73873" x="16.11921" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="0" fill="#999999">?</text>
 </g>
</svg>'