printing
iconSVG

	^'<svg width="32" height="32" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <!-- Created with SVG-edit - http://svg-edit.googlecode.com/ -->
 <g>
  <title>Layer 1</title>
  <line transform="rotate(45 6.78961 20.1255)" id="svg_13" y2="12.717102" x2="6.789612" y1="27.533814" x1="6.789612" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="4" stroke="#999999" fill="none"/>
  <line id="svg_21" transform="rotate(45 24.7307 24.5971)" y2="17.188824" x2="24.730679" y1="32.005535" x1="24.730679" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="4" stroke="#999999" fill="none"/>
  <ellipse stroke="#999999" ry="7.007904" rx="7.007904" id="svg_4" cy="8.378876" cx="18.202484" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="2" fill="none"/>
  <line id="svg_22" transform="rotate(-45 24.5972 24.7307)" y2="17.322308" x2="24.597195" y1="32.139019" x1="24.597195" stroke-linecap="null" stroke-linejoin="null" stroke-dasharray="null" stroke-width="4" stroke="#999999" fill="none"/>
 </g>
</svg>'